name: "update-changelog"

on:
  release:
    types:
      - published

permissions:
      contents: write

jobs:
  terraform:
    uses: schubergphilis/mcaf-github-workflows/.github/workflows/pr-validation.yml@main
    secrets:
      mcaf-github-token: ${{secrets.MCAF_GITHUB_TOKEN}}
